name: CI Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            gu-binary: gu
            suffix: linux
          - os: macos-latest
            gu-binary: gu
            suffix: macos
          - os: windows-latest
            gu-binary: gu.cmd
            suffix: win
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        name: Setup windows environment if needed
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: '21.1.0'
          java: 'java11'
          arch: 'amd64'
      - name: Install native-image component
        run: |
          ${{ matrix.gu-binary }} install native-image

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Maven
        run: mvn --batch-mode verify -Dnative

      - uses: actions/upload-artifact@v2
        with:
          name: exaq-${{ matrix.suffix }}
          path: |
            target/*-runner
            target/*-runner.exe
